# Generated by Django 2.1.7 on 2021-01-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210109_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Отгрузка', 'Отгрузка'), ('Доставка', 'Доставка')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Продукты', 'Продукты'), ('Животные', 'Животные')], max_length=200, null=True),
        ),
    ]
